apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-efs-db
  labels:
    type: efs
spec:
  storageClassName: efs-sc
  claimRef:
    name: pvc-efs-db
    namespace: default
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: ${id_efs}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-efs-db
  namespace: default
spec:
  storageClassName: efs-sc
  volumeName: pv-efs-db
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi