FROM php:8.2-apache-bookworm

RUN apt-get update && apt-get install -y \
    wget \
    ca-certificates \
    apt-transport-https \
    gnupg \
    openssl

RUN wget -O /tmp/powershell.deb https://github.com/PowerShell/PowerShell/releases/download/v7.5.4/powershell_7.5.4-1.deb_amd64.deb \
    && apt-get update \
    && apt-get install -y /tmp/powershell.deb \
    && rm /tmp/powershell.deb \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get purge -y --auto-remove \
    wget \
    apt-transport-https \
    gnupg

# Instalar Módulo de PNP.Powershell
RUN pwsh -command Install-Module -name PNP.Powershell -force

# Habilitar módulos apache necesarios
RUN a2enmod ssl
RUN a2enmod rewrite

# Crear directorio SSL
RUN mkdir /etc/apache2/ssl

# Copiar configuración SSL personalizada tras cambiar las variables por valores
COPY https-var.conf /etc/apache2/sites-available/https.conf

# Habilitar sitio SSL
RUN a2ensite https.conf

# Exponer puertos
EXPOSE 80
EXPOSE 443
