FROM php:8.2-apache-bookworm

RUN apt-get update && apt-get install -y \
    ca-certificates \
    openssl

# Habilitar módulos apache necesarios
RUN a2enmod ssl
RUN a2enmod rewrite

# Crear directorio SSL
RUN mkdir /etc/apache2/ssl

COPY HTML /var/www/html
# Copiar configuración SSL personalizada tras cambiar las variables por valores
COPY Docker/apache/https-var.conf /etc/apache2/sites-available/https.conf
COPY servidor.key /etc/apache2/ssl/servidor.key
COPY servidor.crt /etc/apache2/ssl/servidor.crt

RUN chmod 600 /etc/apache2/ssl/servidor.key
RUN chmod 644 /etc/apache2/ssl/servidor.crt

# Habilitar sitio SSL
RUN a2ensite https.conf

# Exponer puertos
EXPOSE 80
EXPOSE 443
