apiVersion: v1
kind: Service
metadata:
  name: servicio-apache
spec:
  type: LoadBalancer
  selector:
    app: pod-apache
  ports:
    - name: puerto-http
      port: 80
      targetPort: http
    - name: puerto-https
      port: 443
      targetPort: https
