apiVersion: apps/v1
kind: Deployment
metadata:
  name: despliegue-apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-apache
  template:
    metadata:
      labels:
        app: pod-apache
    spec:
      containers:
        - name: contenedor-apache
          image: $ImagenApache
          imagePullPolicy: IfNotPresent
          env:
            - name: API_USER
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: API_USER
            - name: API_PASS
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: API_PASS
          ports:
            - name: http
              containerPort: 80
            - name: https
              containerPort: 443