apiVersion: apps/v1
kind: Deployment
metadata:
  name: despliegue-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-mysql
  template:
    metadata:
      labels:
        app: pod-mysql
    spec:
      containers:
        - name: contenedor-mysql
          image: mysql-php:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
          ports:
            - containerPort: 3306
