apiVersion: apps/v1
kind: Deployment
metadata:
  name: despliegue-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-mysql
  template:
    metadata:
      labels:
        app: pod-mysql
    spec:
      containers:
        - name: contenedor-mysql
          image: $ImagenMysql
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: MYSQL_PASS
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: volumen-db
              mountPath: /var/lib/mysql
      volumes:
        - name: volumen-db
          persistentVolumeClaim:
            claimName: pvc-efs-db