FROM mcr.microsoft.com/powershell:7.4-debian-12

RUN apt-get update && apt-get install -y \
    default-mysql-client

RUN pwsh -Command "\
    Set-PSRepository PSGallery -InstallationPolicy Trusted; \
    Install-Module PnP.PowerShell -Scope AllUsers -Force; \
    Install-Module ThreadJob -Scope AllUsers -Force"

RUN mkdir /certs/ && chmod 700 /certs
COPY scripts/* /scripts/
RUN chmod +x /scripts/*

CMD ["pwsh","/scripts/escaneo.ps1"]