name: 'Destruir Terraform'
on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Destruir Terraform'
    runs-on: ubuntu-latest

    steps:
    # Importar Checkout para cargar el repositorio en el runner
    - name: Checkout
      uses: actions/checkout@v6
      with:
        # Para importar el repositorio se necesita generar un token en github
        token: ${{ secrets.TOKEN_GITHUB }}
    - name: Mover archivos terraform
      run: mv Terraform/* ./
    # Importamos Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4
    # Cargamos las credenciales de AWS para usar awscli
    - name: CONFIGURAR CREDENCIALES AWS
      uses: aws-actions/configure-aws-credentials@v6
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ vars.AWS_REGION }}
    # Importamos Python
    - name: Importar python
      uses: actions/setup-python@v6
      with:
        python-version: '3.10'
    # Descargar terraform.tfstate mediante awscli
    - name: Descargar fichero de s3
      run: |
        python -m pip install --upgrade pip
        pip install awscli
        aws s3 cp s3://${{ vars.AWS_S3 }}/Terraform/terraform.tfstate ./ --region ${{ vars.AWS_REGION }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

    # Iniciar el módulo de terraform en el workflow
    - name: Terraform Init
      run: terraform init
    # Destruimos la ingraestructura
    - name: Terraform Destroy
      run: terraform apply --destroy --auto-approve
    # Borramos el tfstate del s3
    - name: Borrar Caché
      run:  |
          aws s3 rm s3://${{ vars.AWS_S3 }}/Terraform/terraform.tfstate

