name: 'Lanzar Terraform'
on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Lanzar Terraform'
    runs-on: ubuntu-latest

    steps:
    # Importar Checkout para cargar el repositorio en el runner
    - name: Cargar Repositorio al Workflow
      uses: actions/checkout@v6
      with:
        # Para importar el repositorio se necesita generar un token en github
        token: ${{ secrets.TOKEN_GITHUB }}
    - name: Mover archivos terraform
      run: |
        mv Terraform/* ./
        openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout server.key -out server.crt -subj "/C=${{ vars.PAIS }}/CN=${{ vars.HTTP_ALIAS }}"
    # ------------------------------- Importar python para instalar awscli -------------------------------
    - name: Importar python
      uses: actions/setup-python@v6
      with:
        # Con la versión 3.10 no hay fallos de repositorios con awscli
        python-version: '3.10'
    - name: Instalar awscli para subir ficheros al S3
      run: |
        python -m pip install --upgrade pip
        pip install awscli
    # Cargamos las credenciales de AWS para usar awscli y terraform
    - name: Configurar Credenciales AWS
      uses: aws-actions/configure-aws-credentials@v6
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ vars.AWS_REGION }}

    # ------------------------------- Terraform -------------------------------
    # Cargamos el .tfstate del bucket si ya existe
    - name: Cargar .tfstate si ya existe en el bucket
      run: aws s3 cp s3://${{ vars.AWS_S3 }}/Terraform/terraform.tfstate ./ --region ${{ vars.AWS_REGION }}
      continue-on-error: true
    # Iniciar el módulo de terraform en el workdir por defecto
    - name: Cargar Terraform
      uses: hashicorp/setup-terraform@v4
    - name: Iniciar Terraform
      run: terraform init
    # Ejecutamos terraform apply para crear la infrestructura
    - name: Aplicar Terraform
      id: terraform
      run: terraform apply --auto-approve
      continue-on-error: true

    # Guardamos el .tfstate en un bucket creado personalmente en una cuenta AWS
    # En un secret se almacena el nombre del bucket por ejemplo: mi-cubo
    - name: Guardar .tfstate en el Bucket
      run: aws s3 cp terraform.tfstate s3://${{ vars.AWS_S3 }}/Terraform/ --region ${{ vars.AWS_REGION }}
    # Con esto permitimos que el tfstate se guarde con lo que sí se ha creado pero salimos para que no continue
    - name: Salir si falla terraform
      if: ${{ steps.terraform.outcome == 'failure' }}
      run: exit 1

    # Exportar las variables de terraform a variables del sistema
    - name: Exportar variables terraform
      run: |
        if ! command -v jq &> /dev/null; then
          sudo apt install jq -y
        fi
        TF_OUTPUT=$(terraform output -json)
        echo "$TF_OUTPUT" | jq -r 'to_entries[] | "export " + .key + "=" + (if .value.value|type == "array" then "\"" + (.value.value | join(",")) + "\"" else "\"" + (.value.value | tostring) + "\"" end)' > variables-terraform.sh
        chmod +x variables-terraform.sh

    # ------------------------------- Variables de archivos -------------------------------
    # Cargamos usando los secrets y variables de github para reemplazar las variables de entorno y de cada fichero
    - name: Reemplazar variables dentro de los ficheros correspondientes con las variables de entorno
      run: |
        source variables-terraform.sh
        ID_ECR=$(aws sts get-caller-identity --query Account --output text)
        export NombreServidor=${{ vars.HTTP_SERVER }}
        export AliasServidor=${{ vars.HTTP_ALIAS }}
        export ImagenApache=$ID_ECR.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/apache/${{ vars.ECR_Repo }}:latest
        export ImagenMysql=$ID_ECR.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/mysql/${{ vars.ECR_Repo }}:latest

        envsubst "$(printf '${%s} ' $(env | cut -d'=' -f1))" < Docker/apache/https.conf | tee Docker/apache/https-var.conf
        envsubst "$(printf '${%s} ' $(env | cut -d'=' -f1))" < Kubernetes/despliegues/apache.yml | tee apache-var.yml
        envsubst "$(printf '${%s} ' $(env | cut -d'=' -f1))" < Kubernetes/despliegues/mysql.yml | tee mysql-var.yml
        envsubst "$(printf '${%s} ' $(env | cut -d'=' -f1))" < Kubernetes/volumenes/VP-DB.yml | tee VP-DB-var.yml
        envsubst "$(printf '${%s} ' $(env | cut -d'=' -f1))" < Kubernetes/volumenes/VP-HTML.yml | tee VP-HTML-var.yml
    # ------------------------------- ECR Docker -------------------------------
    # Iniciamos sesión en docker con aws ECR ya creado donde almacenaremos las imágenes creadas en AWS
    - name: Subir imágenes docker a ECR de AWS
      run: |
        ID_ECR=$(aws sts get-caller-identity --query Account --output text)
        aws ecr get-login-password --region ${{ vars.AWS_REGION }} | docker login --username AWS --password-stdin $ID_ECR.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com
        
        export ImagenApache=${{ secrets.AWS_ACCESS_KEY_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/apache/${{ vars.ECR_Repo }}:latest
        export ImagenMysql=${{ secrets.AWS_ACCESS_KEY_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com/mysql/${{ vars.ECR_Repo }}:latest
        
        docker build -t $ImagenApache ./Docker/apache
        docker build -t $ImagenMysql ./Docker/mysql
    # ------------------------------- EKS Kubernetes -------------------------------
    # Instalamos eksctl y kubectl
    - name: Instalar y configurar eksctl y kubectl
      run: |
        ARCH=amd64
        PLATFORM=$(uname -s)_$ARCH

        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        mkdir -p $HOME/bin && cp kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH

        curl -LO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"
        tar -xzf eksctl_$PLATFORM.tar.gz
        mv eksctl /usr/local/bin
    # ------------------------------- Kubectl -------------------------------
    # Conectamos kubectl con el cluster para crear el despliegue de apache y mysql
    - name: Conectar kubectl con cluster y desplegar apache y mysql al EKS
      run: |
        source variables-terraform.sh
        aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name $nombre_cluster

        ### Creamos el secret de la contraseña de mysql
        kubectl create secret generic mysql --from-literal=MYSQL_PASS=${{ secrets.MYSQL_ROOT_PASSWORD }}
        
        ####### Añadimos los drivers de csi para volumenes en efs #######
        kubectl apply -k "github.com/kubernetes-sigs/aws-efs-csi-driver/deploy/kubernetes/overlays/stable/ecr/?ref=release-1.5"

        kubectl apply -f Kubernetes/volumenes/CSI-Ext.yml
        kubectl apply -f VP-DB-var.yml
        kubectl apply -f VP-HTML-var.yml
        kubectl wait --for=condition=Bound pvc/pvc-efs-db --timeout=60s
        kubectl wait --for=condition=Bound pvc/pvc-efs-html --timeout=60s

        kubectl apply -f apache-php-var.yml
        kubectl apply -f mysql-var.yml
        kubectl wait --for=condition=Available deployment/despliegue-apache --timeout=120s
        kubectl wait --for=condition=Available deployment/despliegue-mysql --timeout=120s

        kubectl apply -f Kubernetes/servicios/apache.yml
        kubectl apply -f Kubernetes/servicios/mysql.yml


        for pod in $(kubectl get pods -l app=pod-apache -o name); do
          kubectl cp server.key $pod:/etc/apache2/ssl/server.key
          kubectl cp server.crt $pod:/etc/apache2/ssl/server.crt
          kubectl exec $pod -- chmod 600 /etc/apache2/ssl/server.key
          kubectl exec $pod -- chmod 644 /etc/apache2/ssl/server.crt
        done
        kubectl exec $(kubectl get pods -l app=pod-mysql -o name) -- mysql -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} < Docker/mysql/crear-database.sql

        kubectl get svc servicio-apache
